name: proposal
favicon: null
layout_spectrum: 0.9757174104452133
typography_spectrum: 0.31981212575919926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.14118110435083508
  lightness: 0.7674705777317286
  saturation: 0.7638502207119018
  rhythmicContrast: 0.8572173488792032
purpose: []
